### ISSUE TITLE
Calidad de contenido - imágenes de mala calidad

### ISSUE THREAD

**Issue by philbone** [proinchile/CodigosDeConducta#16]
Me he percatado que algunos miembros del grupo de facebook hacen publicaciones con imágenes adjuntas con salidas de error o mensajes de una pantalla.

El problema es que la mayoría son ilegibles. Apelando la calidad del contenido, pensaba en especificar que imágenes con mala calidad o ilegibles son causal de eliminación del post.

Voy a crear una [rama](https://github.com/proinchile/CodigosDeConducta/tree/issue-%2316) nueva para trabajar en esta idea.

;)

**Comment by diruzcode** [comment]
Buena acotación, por tiempo no he podido subir un mani manual del como realizar las preguntas, el cual es bastante necesario, actualmente hay muchas preguntas y de verdad uno se pregunta que es lo que necesita esta persona ..... no entiendo ni coñ....
