### ISSUE TITLE
Pauta laboral - Inclusión de especificación para remuneración liquida/bruta

### ISSUE THREAD

**Issue by philbone** [proinchile/CodigosDeConducta#19]
Un miembro levantó una inquietud acerca de incluir un campo dentro de la pauta de ofertas laborales, para especificar si la remuneración ofrecida es bruta o liquida.

Deberíamos decidir si es necesaria esta especificación y en que casos aplica, si es que la incluimos.

**Comment by carlosromanxyz** [comment]
Líquido siempre

**Comment by alejandroivan** [comment]
Siempre líquido, concuerdo. Sin embargo, hay que dejarlo explícito en la pauta.

**Comment by diruzcode** [comment]
Creo que lo mejor siempre es liquido, al menos en mi experiencia siempre he negociado el liquido ya que el bruto es un poco engañoso

**Comment by prulloac** [comment]
Para claridad de un postulante, es mejor siempre hablar del sueldo líquido

**Comment by rabindranathfv** [comment]
Liquido siempre, mas directo y efectivo

**Comment by 00guille** [comment]
debe quedar explicito en las reglas que la remuneración ofrecida es liquida

**Comment by diruzcode** [comment]
Creo que podemos dar por cerrado este issues y agregaremos a la pauta que el sueldo a de ser liquido siempre.

Saludos
